#!/bin/bash
# inject the git version at the end of the third line (the "date" line)
version=$(git describe --tags 2>/dev/null || git rev-list HEAD -1 | cut -c-7) && sed "3s/$/ | \\\\code{$version}/g" || cat
